services:
  app:
    build:
      context: ../project_app
      args:
        - PORT=3000
        - VITE_API_URL=$API_URL
    ports:
      - 80:3000
    restart: on-failure
    depends_on:
      - api
  api:
    build:
      context: ../project_api
      args:
        - PORT=:$API_PORT
        - GIN_MODE=release
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ../data:/app/data
  db:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME

